#Disable all channels logic. If true amount of used channels is always 0.
DisableChannels = true

[Cells]
	PortableCellFireResistance = false
	CellExplosionResistance = false
	ItemsPerByte = 8
	MbPerByte = 8000
	PortableCellExplosionResistance = false
	CellFireResistance = false

[Controllers]
	#Control all controller limits. If is false, any variant of controller structure is correct.
	ControllerLimits = true
	#If is false, possible structure with cross pattern, i.e. two neighbors on two or three axes.
	ControllerCross = false
	#If is true, possible connect to one me net multiple controller structure.
	MultipleControllers = false

	[Controllers.ControllerSizeLimits]
		Max_Y = 7
		Max_Z = 7
		Max_X = 7

