
#General settings
[general]
    #The CurseForge project ID for the modpack
    #Range: > 0
    modpackProjectID = 0
    #The name of the modpack
    modpackName = "Bigges Pack Cat Edition V - 1.16.5"
    #The version of the modpack
    modpackVersion = "V1.23"
    #Use the metadata.json to determine the modpack version
    #ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
    useMetadata = false