#    Damage multiplier applied to all Hamon attacks.
#Range: 0.0 ~ 128.0
hamonDamageMultiplier = 1.0
#    Whether or not blocks which can be restored by Crazy Diamond's terrain restoration ability are saved in the save files.
#     It may cause longer saving & loading time for larger worlds.
saveDestroyedBlocks = false
#    Disable this if you're boring.
endermenBeyondTimeSpace = true

["Keep Powers After Death"]
	keepHamonOnDeath = true
	#    The weak vampirism version from the 'Blood Gift' ability will not be kept.
	keepVampirismOnDeath = true
	keepStandOnDeath = true
	#    If enabled, Stand users drop their Stand's Disc upon death.
	#    Works only when keepStandOnDeath is set to false.
	dropStandDisc = false

["Structures Spawn"]
	hamonTempleSpawn = true
	meteoriteSpawn = true
	pillarManTempleSpawn = true

# Settings which affect the speed of Hamon training.
["Hamon training"]
	#    Hamon Strength and Control levels growth multiplier.
	#Range: 0.0 ~ 5000.0
	hamonPointsMultiplier = 1.0
	#    Breathing technique growth multiplier.
	#Range: 0.0 ~ 100.0
	breathingTechniqueMultiplier = 1.0
	#    Whether or not breathing technique deteriorates over time.
	breathingTechniqueDeterioration = true

["Vampirism settings"]
	#    Max vampire energy multiplier on each difficulty level.
	maxBloodMultiplier = [1.0, 1.0, 1.0, 1.0]
	#    Blood drain multiplier on each difficulty level.
	bloodDrainMultiplier = [0.0, 1.0, 1.75, 2.5]
	#    Vampire energy decrease per tick on each difficulty level.
	bloodTickDown = [0.13889, 0.00278, 0.00278, 0.0]
	#    Vampire energy cost per 1 hp of healing on each difficulty level.
	bloodHealCost = [10.0, 4.0, 2.0, 1.0]
	#    Whether or not undead mobs take damage under the sun similarly to vampires.
	undeadMobsSunDamage = false

# Settings of Stand Arrow and the Stands pool.
["Stand Arrow"]
	#    If enabled, random Stand gain effects (Stand Arrow, /stand random) give Stands that less players already have.
	#    Otherwise the Stand selection is random.
	prioritizeLeastTakenStands = false
	#    List of Stands excluded from Stand Arrow and /stand random pool.
	#    These stands will still be available via /stand give command
	#    Their Discs won't be added to the mod's Creative tab, but they can still be found in the Search tab (although they can't be used to gain a banned Stand)."
	#    The format is the same as for /stand give command (e.g., "jojo:star_platinum").
	bannedStands = ["jojo:example_1", "jojo:example_2"]
	#    Whether or not the Stand tiers mechanic is enabled.
	standTiers = true
	#    Experience levels nesessary to get a Stand from each tier.
	#    If the list is shorter than the default, next tiers use the last value.
	#    For example, if the list only contains number 15, you'll be able to get any Stand as long as you have 15 experience levels.
	#    Making a value lower that the previous one might lead to an unexpected result.
	standTierXpLevels = [0, 1, 5, 10, 20, 30, 45]

["Stand settings"]
	#    Whether or not Stands and abilities can break blocks.
	abilitiesBreakBlocks = true
	#    Damage multiplier applied to all Stands.
	#Range: 0.0 ~ 128.0
	standPowerMultiplier = 1.0
	#    Whether or not Stand stamina mechanic is enabled.
	standStamina = true
	soulAscension = true

	["Stand settings"."Stand Progression"]
		#    Whether or not all of the abilities are unlocked after gaining a Stand in Survival.
		skipStandProgression = false
		#    Max resolve points at each Resolve level (starting from 0).
		#    Decrease these values to make getting to each level easier.
		#    All values must be higher than 0.
		resolveLvlPoints = [2500.0, 10000.0, 25000.0, 50000.0, 32500.0]

	["Stand settings"."Time Stop"]
		#    Range of Time Stop ability in chunks.
		#     If set to 0, the whole dimension is frozen in time.
		#     Defaults to 12.
		#Range: > 0
		timeStopChunkRange = 12
		#    Damage multiplier for entities frozen in time.
		#Range: 0.0 ~ 1000000.0
		timeStopDamageMultiplier = 1.0

