ignoredNamespaces = []
#Disable generating advancements to accelerate loading and save memories.
disableAdvancements = false
#Forge will load data pack twice, which the first time is unnecessary for Kaleido.
skipFirstTimeDataLoading = true

[modules]
	mallet = true
	chisel = true
	brush = true
	scope = true
	carpentry = true
	hub = true
	preview = true

[carpentry]
	#Only available if disableAdvancements is false
	autoUnlock = true

[debugWorld]
	patch = true
	#Range: 1 ~ 10
	spacing = 3

[scope]
	#Range: > 1
	stackLimit = 8

