
#
#Gui interactions
[guis]
	#
	#Whether to swap the mouse buttons for filling and emptying tanks in machine GUIs. Default is right click to fill and left click to empty.
	swapMouseButtonsForTanks = false

