
#Frequency and height values for ores.
[ores]
	#
	#Whether to generate ores at all.
	generateOres = true
	#
	#Biomes to generate ores in.
	oreBiomes = ["minecraft:ocean", "minecraft:plains", "minecraft:desert", "minecraft:mountains", "minecraft:forest", "minecraft:taiga", "minecraft:swamp", "minecraft:river", "minecraft:frozen_ocean", "minecraft:frozen_river", "minecraft:snowy_tundra", "minecraft:snowy_mountains", "minecraft:mushroom_fields", "minecraft:mushroom_field_shore", "minecraft:beach", "minecraft:desert_hills", "minecraft:wooded_hills", "taiga_hills", "minecraft:mountain_edge", "minecraft:jungle", "minecraft:jungle_hills", "minecraft:jungle_edge", "minecraft:deep_ocean", "minecraft:stone_shore", "minecraft:snowy_beach", "minecraft:birch_forest", "minecraft:birch_forest_hills", "minecraft:dark_forest", "minecraft:snowy_taiga", "snowy_taiga_hills", "minecraft:snowy_taiga_hills", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "minecraft:wooded_mountains", "minecraft:savanna", "minecraft:savanna_plateau", "minecraft:badlands", "minecraft:wooded_badlands_plateau", "minecraft:badlands_plateau", "minecraft:warm_ocean", "minecraft:lukewarm_ocean", "minecraft:cold_ocean", "minecraft:deep_warm_ocean", "minecraft:deep_lukewarm_ocean", "minecraft:deep_cold_ocean", "minecraft:deep_frozen_ocean", "minecraft:sunflower_plains", "minecraft:desert_lakes", "minecraft:gravelly_mountains", "minecraft:flower_forest", "minecraft:taiga_mountains", "minecraft:swamp_hills", "minecraft:ice_spikes", "minecraft:modified_jungle", "minecraft:modified_jungle_edge", "minecraft:tall_birch_forest", "minecraft:tall_birch_hills", "minecraft:dark_forest_hills", "minecraft:snowy_taiga_mountains", "minecraft:giant_spruce_taiga", "minecraft:giant_spruce_taiga_hills", "minecraft:modified_gravelly_mountains", "minecraft:shattered_savanna", "minecraft:shattered_savanna_plateau", "minecraft:eroded_badlands", "minecraft:modified_wooded_badlands_plateau", "minecraft:modified_badlands_plateau", "minecraft:bamboo_jungle", "minecraft:bamboo_jungle_hills"]
	#
	#The size of each ore vein that generates.
	#Range: > 0
	copperVeinSize = 6
	#Range: > 0
	tinVeinSize = 6
	#Range: > 0
	leadVeinSize = 6
	#Range: > 0
	thoriumVeinSize = 4
	#Range: > 0
	uraniumVeinSize = 4
	#Range: > 0
	boronVeinSize = 5
	#Range: > 0
	lithiumVeinSize = 5
	#Range: > 0
	magnesiumVeinSize = 5
	#
	#The frequency of each ore vein within the valid range.
	#Range: > 0
	copperVeinFrequency = 5
	#Range: > 0
	tinVeinFrequency = 4
	#Range: > 0
	leadVeinFrequency = 6
	#Range: > 0
	thoriumVeinFrequency = 4
	#Range: > 0
	uraniumVeinFrequency = 4
	#Range: > 0
	boronVeinFrequency = 6
	#Range: > 0
	lithiumVeinFrequency = 6
	#Range: > 0
	magnesiumVeinFrequency = 4
	#
	#The minimum Y value for a vein to spawn in.
	#Range: > 0
	copperVeinMin = 0
	#Range: > 0
	tinVeinMin = 0
	#Range: > 0
	leadVeinMin = 0
	#Range: > 0
	thoriumVeinMin = 0
	#Range: > 0
	uraniumVeinMin = 0
	#Range: > 0
	boronVeinMin = 0
	#Range: > 0
	lithiumVeinMin = 0
	#Range: > 0
	magnesiumVeinMin = 0
	#
	#The maximum Y value for a vein to spawn in.
	#Range: > 0
	copperVeinMax = 48
	#Range: > 0
	tinVeinMax = 40
	#Range: > 0
	leadVeinMax = 36
	#Range: > 0
	thoriumVeinMax = 32
	#Range: > 0
	uraniumVeinMax = 32
	#Range: > 0
	boronVeinMax = 28
	#Range: > 0
	lithiumVeinMax = 28
	#Range: > 0
	magnesiumVeinMax = 24

