drop_after_ticks = 2400
despawn_corps_after_ticks = 4800
despawn_immediately_when_empty = true
surfacing_in_water = true
drop_unlooted = false
hopper_extracting = false
#Example: minecraft:zombie or adventurez.brown_fungus
excluded_entities = []

