
#Items
[items]
	#The default payment item. Format is "namespace:item"
	payment_item = "vendingmachine:money"
	#Set to true if prices are per-stack and not per-item
	is_stack_price = false
	#Set to true if players can edit item prices per-machine.
	allow_editing = false
	#Set to false if you don't want players to be able to remote control their machines.
	allow_rc = true
	#Set to 0 if you don't want to give new players money, else set to the amount of money to give new players
	spawn_money = 128
	#Item prices. Format is "namespace:item price"
	item_prices = ["minecraft:dirt 1"]

