
#WorldGen settings
[worldGen]

	#Aluminium
	[worldGen.aluminium]
		#Defines the amount of veins per chunk
		#Range: 0 ~ 256
		amount = 8
		#Defines the maximum amount of blocks in a vein
		#Range: 0 ~ 64
		size = 8
		#Defines the maximum height at which a vein can be generated
		#Range: 0 ~ 256
		maxHeight = 64

	#Quartz Crystal
	[worldGen.quartzCrystalCluster]
		#Defines the maximum amount per chunk
		#Range: 0 ~ 64
		amount = 4
		#Defines the amount of attempts to generate per chunk
		#Range: 0 ~ 256
		generationAttempts = 64
		#Defines the maximum amount of crystals per cluster
		#Range: 1 ~ 5
		maxCrystals = 5

	#Zychorite
	[worldGen.zychorite]
		#Defines the amount of veins per chunk
		#Range: 0 ~ 256
		amount = 8
		#Defines the maximum amount of blocks in a vein
		#Range: 0 ~ 64
		size = 17
		#Defines the maximum height at which a vein can be generated
		#Range: 0 ~ 256
		maxHeight = 64
		#Defines the percentage of the vein that will be filled with Zychorium Ore's
		#Range: 0 ~ 100
		orePercentage = 50

