
#
# This is 1 of ZAWA's 10 habitat ranges. Each sub-range has its own list of biomes, and all of the sub-range's entities will spawn in those biomes.
# Disable entities (or a species variant) by setting "enabled" under their category to false.
# Use ONLY whole numbers greater than 0 for chance, min, and max!
# "chance" is how common they spawn, a higher number is more common than a lower number. "min" and "max" adjusts their spawning group size.
# !! If modded biomes are not generated, delete the entire "biomes" line for each sub-category and restart minecraft. !!
#
#
[coastal_taiga]
	biomes = ["minecraft:taiga", "minecraft:giant_tree_taiga", "biomesoplenty:coniferous_forest", "biomesoplenty:coniferous_lakes", "biomesoplenty:fir_clearing", "biomesoplenty:flower_meadow", "biomesoplenty:meadow", "biomesoplenty:meadow_forest", "biomesoplenty:ominous_woods", "biomesoplenty:ominous_mire", "projectvibrantjourneys:redwoods", "projectvibrantjourneys:boreal_forest", "projectvibrantjourneys:pine_meadows", "projectvibrantjourneys:autumnal_coniferous_forest", "projectvibrantjourneys:crimson_thicket", "projectvibrantjourneys:crystal_lakes", "traverse:coniferous_forest", "graveyard:haunted_forest", "graveyard:haunted_lakes", "graveyard:eroded_haunted_forest", "terraforged:fir_forest", "terraforged:taiga_scrub", "minecraft:beach", "minecraft:stone_shore", "minecraft:snowy_beach", "biomesoplenty:gravel_beach", "projectvibrantjourneys:gravel_shore", "projectvibrantjourneys:tropical_beach", "projectvibrantjourneys:windswept_shore", "terrestria:caldera_beach"]

	[coastal_taiga.bald_eagle]
		chance = 8
		min = 1
		max = 1
		enabled = true

