
#
# This is 1 of ZAWA's 10 habitat ranges. Each sub-range has its own list of biomes, and all of the sub-range's entities will spawn in those biomes.
# Disable entities (or a species variant) by setting "enabled" under their category to false.
# Use ONLY whole numbers greater than 0 for chance, min, and max!
# "chance" is how common they spawn, a higher number is more common than a lower number. "min" and "max" adjusts their spawning group size.
# !! If modded biomes are not generated, delete the entire "biomes" line for each sub-category and restart minecraft. !!
#
#
[inland_tundra]
	biomes = ["minecraft:snowy_tundra", "minecraft:snowy_mountains", "minecraft:snowy_taiga", "minecraft:snowy_taiga_mountains", "biomesoplenty:alps_foothills", "biomesoplenty:alps", "biomesoplenty:cold_desert", "biomesoplenty:muskeg", "biomesoplenty:snowy_coniferous_forest", "biomesoplenty:snowy_maple_forest", "biomesoplenty:snowy_fir_clearing", "projectvibrantjourneys:snowy_redwoods", "projectvibrantjourneys:snowy_boreal_forest", "projectvibrantjourneys:alpine_heights", "projectvibrantjourneys:boreal_plateau", "demon_realm:boiling_titan_knee", "demon_realm:boiling_extreme_titan_peak", "traverse:snowy_coniferous_forest", "terraforged:cold_marshland", "terraforged:frozen_marsh", "terraforged:snowy_fir_forest", "terraforged:snowy_taiga_scrub", "twilightforest:snowy_forest", "twilightforest:glacier", "the_mm:the_dark_forest"]

[coastal_tundra]
	biomes = ["minecraft:frozen_ocean", "minecraft:frozen_river", "minecraft:snowy_beach", "minecraft:ice_spikes", "biomesoplenty:cold_desert", "biomesoplenty:muskeg", "terraforged:frozen_lake", "the_mm:the_dark_forest", "terrestria:snowy_hemlock_clearing"]

	[coastal_tundra.emperor_penguin]
		chance = 15
		min = 4
		max = 6
		enabled = true

	[coastal_tundra.polar_bear]
		chance = 5
		min = 1
		max = 1
		enabled = true

